# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_outstanding_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrower_term_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_outstanding_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lender_term_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_date', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=30, verbose_name="user's first name")),
                ('user_last_name', models.CharField(max_length=30, verbose_name="user's last name")),
                ('user_email', models.CharField(max_length=100, verbose_name="user's email address")),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_date', models.DateTimeField(verbose_name='date posted')),
                ('transaction_borrower_interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_lender_interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_key', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='lenders',
            name='lender_register_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myP2P_app.Registration'),
        ),
        migrations.AddField(
            model_name='lenders',
            name='transaction_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myP2P_app.Transaction'),
        ),
        migrations.AddField(
            model_name='borrowers',
            name='borrower_register_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myP2P_app.Registration'),
        ),
        migrations.AddField(
            model_name='borrowers',
            name='transaction_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myP2P_app.Transaction'),
        ),
    ]
