# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_outstanding_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrower_term_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrower_interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrower_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_outstanding_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lender_term_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lender_interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lender_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
