# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myP2P_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_email',
            field=models.CharField(max_length=100, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
    ]
